name: parallel-and-concurrent-programming-in-haskell
version: 0.1.0.0
github: "githubuser/parallel-and-concurrent-programming-in-haskell"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/parallel-and-concurrent-programming-in-haskell#readme>

language: GHC2021
dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - TypeApplications
  - ImportQualifiedPost
  - NoStarIsType
  - LambdaCase
  - QuasiQuotes
  - OverloadedStrings
  - NoFieldSelectors
  - OverloadedRecordDot
  - DuplicateRecordFields
  - BlockArguments
  - PackageImports
  - PatternSynonyms
  - DerivingStrategies
  - DerivingVia

library:
  source-dirs: src
  dependencies:
    - parallel
    - text
    - time
    - extra
    - array
    - deepseq
    - vector
    - monad-par
    - bytestring
    - binary
    - random
    - normaldistribution
    - containers
    - http-conduit
    - stm
    - stm-delay
    - network
    - network-uri
    - network-run
    - async

executables:
  parallel-and-concurrent-programming-in-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - parallel-and-concurrent-programming-in-haskell

tests:
  parallel-and-concurrent-programming-in-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - parallel-and-concurrent-programming-in-haskell
